[domain_parameters]
length = 0.01
timestep_over_spatialstep_times_c = 4.5
number_grid_points = 70
number_grid_points_y = 3
number_grid_points_z = 3
total_steps = 1100

[solver_parameters]
field_solver = 0                 # Algorithm to solve E and B fields - 0: Curl_EB, 1: FDTD
time_evolution_algorithm = 0     # Algorithm to evolve particles in time - 0: Boris, 1: implicit Crank-Nicholson
max_number_of_Picard_iterations_implicit_CN = 20
number_of_particle_substeps_implicit_CN = 2
tolerance_Picard_iterations_implicit_CN = 1e-10
print_info = true
relativistic = false
filter_passes = 5
filter_alpha = 0.5
filter_strides = [1, 2, 4]

[external_field_parameters]
external_electric_field_amplitude = 0
external_electric_field_wavenumber = 0

[species_parameters.electrons.electrons0]
number_pseudoparticles = 3500
grid_points_per_Debye_length = 0.50265482457
weight = 0
charge_over_elementary_charge = -1
perturbation_amplitude_x = 0.0000005
perturbation_wavenumber_x = 1
vth_over_c_x = 0.05
drift_speed_x = 6e7
velocity_plus_minus_x = true

[species_parameters.ions.ions0]
number_pseudoparticles = 3500
grid_points_per_Debye_length = 0.50265482457
weight = 0
charge_over_elementary_charge = 1
mass_over_proton_mass = 1
vth_over_c_x = "_electrons0"
vth_over_c_y = "_electrons0"
vth_over_c_z = "_electrons0"
ion_temperature_over_electron_temperature_x = 0.01
ion_temperature_over_electron_temperature_y = 0.01
ion_temperature_over_electron_temperature_z = 0.01
