name: Upload Python Package

on:
  push:
    tags:
      - '**'
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools_scm

      - name: Update version dynamically
        run: |
          # Use setuptools_scm to manage versioning dynamically
          echo "__version__ = '$(python -m setuptools_scm)'" > jaxincell/version.py

      - name: Build distributions
        run: python -m build

      - name: Upload distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  create-tag:
    runs-on: ubuntu-latest
    needs:
      - release-build
    steps:
      - uses: actions/checkout@v4

      - name: Install setuptools_scm
        run: |
          python -m pip install setuptools_scm

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - create-tag
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1